name: Keep Streamlit App Awake

on:
  schedule:
    # 3일마다 자정에 자동으로 실행하여 트래픽 발생
    - cron: '0 0 */3 * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit app
        run: curl -sL https://myevcar.streamlit.app > /dev/null